name: Blocklist-Json-Validation
on:
  push:
  pull_request:
  repository_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:      
    - name: checkout repo content
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.6'
    - name: install python packages
      run: |
        python -m pip install requests
    - name: execute py script
      run: python downloadFromBlocklistCofig.py

    

