name: ValidateBlocklists
on:
  push:
    # TODO: inputs.environment and inputs.commit
    branches:
      - "main"
    tags:
      - "v*"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/blocklistValidate.yml"
      - ".eslintrc.cjs"
      - ".prettierignore"
      - "*.toml"
      - "*.Dockerfile"
      - "*.js"
      - "*/*.js"
      - ".husky/*"
      - ".prettierrc.json"
      - "LICENSE"
      - "README.md"
  pull_request:
  repository_dispatch:
env:
  INDIR: "blocklistfiles"
  OUTDIR: "result"
  S3DIR: "blocklists"
  BLCONFIG: "blocklistConfig.json"
jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: 📃 Checkout repo
      uses: actions/checkout@v2
    - name: 🐉 Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.6'
    - name: 📥 Install deps
      run: |
        python -m pip install aiohttp
    - name: 💯 Validate blocklistconfig.json
      run: python download.py
