name: MakeTrie
on:
  workflow_dispatch:
  repository_dispatch:
    types: custom_event_type
env:
  INDIR: "blocklistfiles"
  OUTDIR: "result"
  S3DIR: "blocklists"
jobs:
  make:
    runs-on: ubuntu-latest
    timeout-minutes: 80
    steps:
    - name: 📃 Checkout repo
      uses: actions/checkout@v2
    - name: 🐉 Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.6'
    - name: ⭕ Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: ⏳ Make swap
      run: |
          free -hm
          # make swap: community.fly.io/t/6782/10
          sudo fallocate -l 24G ./swapfile
          # unix.stackexchange.com/a/297155
          sudo chown root:root ./swapfile
          sudo mkswap ./swapfile
          # stackoverflow.com/a/550808
          sudo cat /proc/sys/vm/swappiness
          echo "20" | sudo tee /proc/sys/vm/swappiness > /dev/null
          # github.com/pierotofy/set-swap-space/blob/master/action.yml
          sudo swapon ./swapfile
          free -hm
      shell: bash
    - name: 📥 Download blocklists
      run: |
        python -m pip install aiohttp
        python download.py
    - name: 🌲 Make compact trie
      run: |
        npm install
        mkdir -p "$OUTDIR"
        # 32768/1024 => 32G RAM
        node --max-old-space-size=32768 --expose-gc build.js
      env:
        OUTDIR: ${{ env.OUTDIR }}
    - name: 🪄 Split trie in 20MB slices
      run: |
        # creates td00.txt, td01.txt, ... , td98.txt, td99.txt, td100.txt, ...
        cd "$OUTDIR" && split -b20000000 -d --additional-suffix=.txt td.txt td
        ls -lhtr # list files
      env:
        OUTDIR: ${{ env.OUTDIR }}
    - name: 📤 Upload compact trie
      run: |
        node upload.js
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        S3DIR: ${{ env.S3DIR }}
        OUTDIR: ${{ env.OUTDIR }}



