name: Blocklist-Creation-S3Upload
on:  
  push:
  pull_request:
  repository_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:      
    - name: checkout repo content
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.6'
    - name: setup node
      uses: actions/setup-node@v2
      with: 
        node-version: '14'      
    - name: Upload blocklist to aws s3
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
      run: |
        npm cache clean --force
        npm update
        npm install -g aws-sdk
        export PATH="/opt/hostedtoolcache/node/14.17.3/x64/lib/:$PATH"
        npm config -ls -l
        node upload.js       
        
    

