name: Blocklist-Creation-S3Upload
on:
  push:
  pull_request:
  repository_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:      
    - name: checkout repo content
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.6'
    - name: setup node
      uses: actions/setup-node@v2
      with: 
        node-version: '14'
    - name : install npm modules
      run : |
        npm cache clean --force
        npm install aws-sdk
    - name: install python packages
      run: |
        python -m pip install requests
    - name: Download blocklist script execution
      run: python download.py
    - name: Build blocklist filter using node
      run: |
        mkdir result
        node --max-old-space-size=12288 build.js        
    - name: Upload blocklist to aws s3
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
      run: |
        node upload.js       
        
    

