name: MakeTrie
on:
  workflow_dispatch:
  repository_dispatch:
    types: custom_event_type
env:
  INDIR: "blocklistfiles"
  OUTDIR: "result"
  S3DIR: "blocklists"
  BLCONFIG: "config.json"
  PREFER_S3_OVER_R2: "false"
jobs:
  make:
    strategy:
      matrix:
        codec: ["u8", "u6"]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: 📃 Checkout repo
      uses: actions/checkout@v2
    - name: 🐉 Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.6'
    - name: ⭕ Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: ⏳ Make swap
      run: |
          free -hm
          # make swap: community.fly.io/t/6782/10
          sudo fallocate -l 24G ./swapfile
          # unix.stackexchange.com/a/297155
          sudo chown root:root ./swapfile
          sudo mkswap ./swapfile
          # stackoverflow.com/a/550808
          sudo cat /proc/sys/vm/swappiness
          echo "20" | sudo tee /proc/sys/vm/swappiness > /dev/null
          # github.com/pierotofy/set-swap-space/blob/master/action.yml
          sudo swapon ./swapfile
          free -hm
      shell: bash
    - name: 📥 Download blocklists
      run: |
        python -m pip install aiohttp
        python download.py
      env:
        BLCONFIG: ${{ env.BLCONFIG }}
    - name: 🌲 Make compact trie
      run: |
        npm install
        mkdir -p "$OUTDIR"
        # 32768/1024 => 32G RAM
        node --max-old-space-size=32768 --expose-gc ./src/build.js
      env:
        BLCONFIG: ${{ env.BLCONFIG }}
        OUTDIR: ${{ env.OUTDIR }}
        INDIR: ${{ env.INDIR }}
        CODEC: ${{ matrix.codec }}
    - name: 🪄 Split trie in 30MB slices
      run: |
        # creates td00.txt, td01.txt, ... , td98.txt, td99.txt, td100.txt, ...
        cd "$OUTDIR" && split --bytes=30M -d --additional-suffix=.txt td.txt td
        ls -lhtr # list files
      env:
        OUTDIR: ${{ env.OUTDIR }}
    - name: 📤 Upload artifacts
      run: |
        node ./src/upload.js
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        CF_ACCOUNT_ID: ${{ env.CF_ACCOUNT_ID }}
        PREFER_S3_OVER_R2: ${{ env.PREFER_S3_OVER_R2 }}
        CODEC: ${{ matrix.codec }}
        S3DIR: ${{ env.S3DIR }}
        OUTDIR: ${{ env.OUTDIR }}
