name: Blocklist-Json-Validation
on:
  push:
  pull_request:
  repository_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: checkout repo content
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.7'
    - name: execute py script
      run: python downloadFromBlocklistCofig.py

